kind: "BuildConfig"
apiVersion: "v1"
metadata:
  name: "icodejava-customers-pipeline"
spec:
  source:
    type: "Git"
    git:
      uri: "https://github.com/donovanmuller/icodejava-customers.git"
  triggers:
    - type: "GitHub"
      github:
        secret: "icodejava"
  strategy:
    type: "JenkinsPipeline"
    jenkinsPipelineStrategy: {}
